dev to main
coretech/n2p-auth-service-client pull request #1
Opened 2022-12-07 13:08 UTC by irempehlivan94

2022-12-08 08:40 UTC, konstantin-smolyakov-idt requested changes

2022-12-08 08:40 UTC, konstantin-smolyakov-idt commented on n2p-auth-service-client/IAuthServiceClient.cs
> +    public interface IAuthServiceClient
**design (blocking)** The idea of any library is to encapsulate some behavior into  a reusable component. For example, we need `BatchGetUsers` in 3 other services and we don't want to write a lot of code to use that.

So I believe the interface should be similar to https://github.com/coretech/n2p-calling-services/blob/dev/src/CallingServices.WebApi/V2/Integrations/AuthService/IAuthServiceClient.cs

2022-12-08 08:40 UTC, konstantin-smolyakov-idt commented on n2p-auth-service-client/IAuthServiceClient.cs
> +﻿namespace N2P.Auth.Service.Client
**style (blocking)** Regarding the namespaces and folders, I would suggest to stick to this structure: https://gist.github.com/davidfowl/ed7564297c61fe9ab814

The main things are:

* `src` for the main source code
* `test` or `tests` for the test source code
* Solution file in the root (to open quickly and generally useful)

2022-12-08 08:40 UTC, konstantin-smolyakov-idt commented on n2p-auth-service-client/Initialize.cs
> +        public static void InitializeAuthServiceClient(this IServiceCollection serviceCollection)
**suggestion (non blocking)** Let's stick to default conventions of Microsoft libraries. They use `AddLogging`, `AddMvc`.

So we can use `AddAuthServiceApiClient`.

2022-12-08 08:40 UTC, konstantin-smolyakov-idt commented on n2p-auth-service-client/Initialize.cs
> +        private static string? GetToken(IServiceCollection services)
**suggestion (blocking)** Let's avoid doing implementation in this PR. So let's stick to defining `IAuthServiceClient`, data models to use in request/response and methods used to configure the client (you can throw `NotImplementedException`).

2022-12-08 08:40 UTC, konstantin-smolyakov-idt commented on n2p-auth-service-client/Initialize.cs
> +                c.BaseAddress = new Uri("BaseUrl"); //Todo
**design (blocking)** This should be configurable. So we should have some options class which will allow to set base URL. We can later make it optional by auto-selecting the URL based on `IHostEnvironment`.

2022-12-08 08:40 UTC, konstantin-smolyakov-idt commented on n2p-auth-service-client/Initialize.cs
> +        public static void InitializeHttpClient(this IServiceCollection serviceCollection)
**design (blocking)** We should keep number of public methods to minimum to make sure the correct way is used to add the library to the DI.

2022-12-08 08:40 UTC, konstantin-smolyakov-idt commented on N2P.Auth.Service.Client.Tests/Model/GetV2ResponseModel.cs
> +    public class GetV2ResponseModel
**question (blocking)** Do we need this here?

2022-12-08 08:40 UTC, konstantin-smolyakov-idt commented on n2p-auth-service-client/BaseResponse.cs
> +        public bool HasError => Errors.Any();
**design (blocking)** Let's use exceptions for error handling. It works much better in .NET because you generally expect an exception when things go wrong. 

For example see: https://github.com/coretech/n2p-calling-services/blob/dev/src/CallingServices.WebApi/V2/Integrations/AuthService/AuthServiceResponseException.cs

2022-12-14 14:35 UTC, konstantin-smolyakov-idt commented on n2p-auth-service-client/Initialize.cs
> +        public static void InitializeHttpClient(this IServiceCollection serviceCollection)
@irempehlivan There are still public classes that shouldn't be public. For example I don't expect anyone to use `IBaseClient` directly even if we need such an abstraction. This is an implementation details and shouldn't be exposed. We also don't need that in this PR (as it's part of the implementation).

2022-12-14 15:36 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/HttpClientTimeoutException.cs
> +        public Type ServiceType { get; }
**design (blocking)** This is now a client library for auth service only, so this doesn't make sense. For a timeout exception I think it makes sense to expose `TimeSpan Timeout` field in addition to default exception message.
```suggestion
        public TimeSpan TimeoutExceeded { get; }
```

2022-12-14 15:37 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/InternalServerErrorModel.cs
> +        internal static InternalServerErrorModel CreateWithDefaultMessage()
**design (blocking)**

Please remove implementation parts from this PR. In the case of the library the message and status code would always come deserialized from the JSON, we don't really need to create errors. 

```suggestion
        internal static InternalServerErrorModel CreateWithDefaultMessage()
```

2022-12-14 15:38 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/ServiceException.cs
> +    public class ServiceException : Exception
**design (blocking)** Looks unrelated to the library? When do we throw this exception?

2022-12-14 15:38 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Http/Serialization/HeaderValueProvider.cs
> +    internal class HeaderValueProvider
**issue (blocking)** Let's remove that, it's not related to the auth server client, it's part of the server implementation.

2022-12-14 15:39 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Http/Serialization/HeaderValueProviderContext.cs
> +    public class HeaderValueProviderContext
**issue (blocking)** Remove this as well (no usages of this in the library?)

2022-12-14 15:40 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Initialize.cs
> +        public static void AddAuthServiceApiClient(this IServiceCollection serviceCollection, IWebHostEnvironment? environment = null)
**design (blocking)** Instead of passing the environment, let's just ask for options we need (a custom options class with BaseUrl, Timeout).

2022-12-14 15:40 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/BaseResponse.cs
> +    public class BaseResponse<TData>
**design (blocking)** This is unused now if we are using exceptions for error handling

2022-12-14 15:43 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/BatchGetUsers/AvatarImageModel.cs
> +        //[JsonConverter(typeof(N2PJsonEnumStringConverter<AvatarImageKind>))]
**style (blocking)** Remove commented out code?

2022-12-14 15:43 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/BatchGetUsers/UserModel.cs
> +        //public RoleModel? Role { get; set; } = default!;
**question (blocking)** Why commented out?

2022-12-14 15:45 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/BatchGetUsers/UserModel.cs
> +    public class UserModel
**issue (blocking)** In order to also carry over additional fields that can be added to the user model, we should add an `ExtensionData` field. This is to make sure we don't have to keep the library updated just to carry over some new field. 

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/handle-overflow?pivots=dotnet-7-0

2022-12-14 15:46 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/BatchGetUsers/UserModel.cs
> +    }
**issue (blocking)**

The `is_deleted` property is available on this model now. Please define the models according to the latest version of the spec.

2022-12-14 15:49 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/ErrorCodeConstants.cs
> +    public static class ErrorCodeConstants
**design (blocking)** We should use error classes for error type checks if we expose them on exception. The constants duplicate the same thing, so we shouldn't expose the same info twice using different concepts.

```
try 
{
   var users = await authServiceClient.BatchGetUsers(...);
} 
catch (AuthServiceErrorResponseException ex) when (ex.Error is ValidationError)  {
} 
```

2022-12-14 15:51 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/Options.cs
> +    public class Options
**desing (blocking)** This is part of the implementation, I would say (how to choose URL if it's not provided in options). So we can replace this with something generic, e.g. 

```
public class AuthServiceOptions 
{
    // If this is null, we'll pickup proper value for you by environment
    public string? BaseUrl {get; set;}

    public TimeSpan Timeout {get; set;} = TimeSpan.FromSeconds(30);
}
```

2022-12-14 15:53 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/AuthService/Interfaces/IAuthServiceClient.cs
> +        Task<Collection<UserModel>> BatchGetUsersAsync(HashSet<string> userIds);
**issue (blocking)** This method now supports including or excluding deleted users. So please use the latest version of the spec to define the client interface.

https://auth-qa.net2phone.com/swagger/index.html?urls.primaryName=N2P%20Auth%20Server%20V2%20API

2022-12-20 09:00 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/AuthService/Interfaces/IAuthServiceClient.cs
> +        Task<Collection<UserModel>> BatchGetUsersAsync(HashSet<string> userIds);
@irempehlivan I still see it's not resolved. The latest API allows to:

1. Include deleted users using `include_deleted` query parameter.
2. Pass an account id with a system token.

So instead of having many parameters, I would suggest to introduce a parameter object like this:

```csharp
public class BatchGetUsersQuery
{
    public IReadOnlyCollection<string> UserIds { get; }
    public bool IncludeDeleted { get; }
    public string? AccountId { get; }
}
```

2022-12-20 09:02 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/ErrorModel.cs
> +        [JsonPropertyName("message")]
@irempehlivan I still see some fields annotated. I think it's much safer to use a global serialization policy so that all fields are converted to `snake_case`. E.g. we'll do it during the implementation like this: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/customize-properties?pivots=dotnet-7-0#use-a-custom-json-property-naming-policy

2022-12-20 09:07 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/BaseResponse.cs
> +    public class BaseResponse<TData>
@irempehlivan I still see this in the code. I expect that to be replaced with custom exceptions we can throw.

2022-12-20 09:10 UTC, konstantin-smolyakov-idt commented on n2p-auth-service-client.sln
>  # Visual Studio Version 17
**style (blocking)** Let's follow .NET standard `PascalCase` naming convention for projects and solution files. So let's rename this to `N2P.AuthServiceClient.sln`

2022-12-20 09:11 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/AuthService/AuthServiceClient.cs
> +public class AuthServiceClient
**design (blocking)** Remove all implementation classes for now, this will go next.

2022-12-20 09:11 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/AuthService/BaseClient.cs
> +internal class BaseClient
**design (blocking)** Remove all implementation classes for now.

2022-12-20 09:12 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/AuthService/Interfaces/IBaseClient.cs
> +    internal interface IBaseClient
**design (blocking)** Remove all implementation classes and interfaces. All internals of the library would go in the next PR.

2022-12-20 09:12 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Common/N2PJsonEnumStringConverter.cs
> +public class N2PJsonEnumStringConverter<T> : JsonConverter<object> where T : Enum
**design (blocking)** Remove implementation-specific classes for now.

2022-12-20 09:14 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/AuthServerKnownErrorResponseException.cs
> +    internal class AuthServerKnownErrorResponseException : AuthServiceResponseException
**design (blocking)** So, if I caught this exception, how do I figure out which exact error happened? I expected to see an `ErrorModel` on this class, so that we can do

```csharp
try
{
     await _client.DoSomething();
}
catch(AuthServerKnownErrorResponseException ex) when (ex.Error is ValidationError validationError) {
}
```

2022-12-20 09:17 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/AuthServerUnknownErrorResponseException.cs
> +    internal class AuthServerUnknownErrorResponseException : AuthServiceResponseException
**design (blocking)** If this error happened, which details we can provide to help with troubleshooting. The unknown error is the one we couldn't parse. So we should include the details here: 

* HTTP status code, 
* Raw response body and headers.
* Operation id (e.g. "BatchGetUsers") 

```csharp
// Pseudocode
{
   try
{
     await _client.DoSomething();
}
catch(AuthServerUnknownErrorResponseException ex) 
{
   _logger.LogError("....", ex.StatusCode, ex.RawResponseBody, ...);
}
```

2022-12-20 09:17 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/AuthServerKnownErrorResponseException.cs
> +    internal class AuthServerKnownErrorResponseException : AuthServiceResponseException
**issue (blocking)** Those must be public, otherwise consumers wouldn't be able to catch these exceptions.

2022-12-20 09:19 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/AuthServerKnownErrorResponseException.cs
> +namespace N2P.Auth.Service.Client.ErrorHandling
**design (blocking)** Usually, for libraries a single or few namespaces are used to avoid breaking changes. E.g. if you as a library author decide to move file between folders, it shouldn't break the code of the clients. 

So let's use `N2P.AuthService.Client` (for interface and options) and `N2P.AuthService.Client.Models` (for data models and exceptions) for all the files in this PR. 

See https://stackoverflow.com/questions/38395826/resharper-override-default-namespace-to-prevent-namespace-does-not-correspond to know how to configure Rider for it.

2022-12-20 09:22 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/ErrorModel.cs
> +    public string Message { get; set; } = default!;
**suggestion (non blocking)** Do we really need to expose those fields as writable? Do we have a use case when you get some error and then need to overwrite it? I think it's safer to have it read-only. I would prefer immutable models (at least for errors), e.g. like this: https://stackoverflow.com/questions/38395826/resharper-override-default-namespace-to-prevent-namespace-does-not-correspond

2022-12-20 09:25 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/HttpClientTimeoutException.cs
> +public class HttpClientTimeoutException : Exception
**design (blocking)** This doesn't match with your XML docs where it should be `AuthServiceTimeoutException`. I would also suggest to derive from `TimeoutException` in this case.

2022-12-20 09:25 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/InternalServerErrorModel.cs
> +    public InternalServerErrorType Type { get; set; } = InternalServerErrorType.InternalServerError;
**design (blocking)** I don't think we need this if we can do `exception.Error is InternalServerErrorModel` instead.

2022-12-20 09:28 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/InternalServerErrorModel.cs
> +public class InternalServerErrorModel : ErrorModel
**design (blocking)** Is it the only error type that can be thrown? We should model all known errors as defined in the spec.

![chrome_8688Mygyvn](https://user-images.githubusercontent.com/82883363/208632057-89a09b07-804d-4986-ad83-7bf4a8834761.png)

So please add `AuthenticationError` and `ValidationError`.

2022-12-20 09:29 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Initialize.cs
> +public static class Initialize
**style (blocking)** Use clear names for public classes
```suggestion
public static class AuthServiceClientDependencyInjectionExtensions
```

2022-12-20 09:29 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/BatchGetUsers/AvatarImageKind.cs
> +    [EnumMember(Value = "original")] Original = 1,
**suggestion (non blocking)** Can we just use a convention as all enums are `snake_case`?

2022-12-20 09:30 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/BatchGetUsers/AvatarImageModel.cs
> +    [JsonConverter(typeof(N2PJsonEnumStringConverter<AvatarImageKind>))]
**design (blocking)** Remove all implementation details from this PR. We'll add necessary JSON configuration when working on implementation. In this PR focus on data model itself, not how to parse it from the request or response.

2022-12-20 09:31 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/BatchGetUsers/UserReferenceModel.cs
> +    [JsonPropertyName("first_name")] public string FirstName { get; set; } = default!;
**design (blocking)**

Isn't this field optional as per spec? 

```suggestion
    [JsonPropertyName("first_name")] public string? FirstName { get; set; } = default!;
```

2022-12-20 09:32 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/RawErrorResponse.cs
> +public class RawErrorResponse
**question (blocking)** Looks like this is unused? Supposed to be used in `AuthServiceUnknownResponseException`?

2022-12-20 09:33 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/N2P.Auth.Service.Client.csproj
> +        <PackageReference Include="FluentAssertions" Version="6.8.0"/>
**design (blocking)** Let's remove all currently unused libraries that we need for implementation and keep this PR free of implementation details.

2022-12-20 09:34 UTC, konstantin-smolyakov-idt commented on tests/N2P.Auth.Service.Client.Tests/AuthServiceClientTest.cs
> +public class AuthServiceClientTest
**suggestion (blocking)** Just remove the test projects? We can add it back when we are ready to write tests.

2022-12-21 13:47 UTC, irempehlivan94 commented on src/n2p-auth-service-client/Model/BaseResponse.cs
> +    public class BaseResponse<TData>
Still, i suppose we should use the execute async methods to avoid from writing same business code again and again.In that case, i have to use base response to return error or data.

2022-12-21 13:58 UTC, irempehlivan94 commented on n2p-auth-service-client.sln
>  # Visual Studio Version 17
**About Authentication** 
I think, We can handle token process like that. I added it in my previous pr but i removed because i deleted AuthServiceClient.cs
```
public static class AuthServiceClientDependencyInjectionExtensions
{
    public static void AddAuthServiceApiClient(this IServiceCollection serviceCollection,
        Action<AuthServiceClientOptions>? configure = null)
    {
        //if (configure != null) serviceCollection.AddOptions<AuthServiceClientOptions>().Configure(configure);
        serviceCollection.AddHttpClient<IAuthServiceClient, AuthServiceClient>(c =>
        {
            c.DefaultRequestHeaders.Add("Accept", "application/json");
            c.DefaultRequestHeaders.Connection.Add("Keep-Alive");

            var bearerToken = GetToken(serviceCollection);

            if (bearerToken != null)
                c.DefaultRequestHeaders.Add("Authorization", bearerToken);

        });
    }
    private static string? GetToken(IServiceCollection services)
    {
        // access the DI container
        var serviceProvider = services.BuildServiceProvider();
        // Find the HttpContextAccessor service
        var httpContextAccessor = serviceProvider.GetService<IHttpContextAccessor>();
        var bearerToken = httpContextAccessor?.HttpContext?.Request
                  .Headers["Authorization"]
                  .FirstOrDefault(h => h.StartsWith("bearer ", StringComparison.InvariantCultureIgnoreCase));
        return bearerToken;
    }
}
```

2022-12-21 14:02 UTC, irempehlivan94 commented on src/n2p-auth-service-client/ErrorHandling/ErrorModel.cs
> +        [JsonPropertyName("message")]
I actually fixed it. It looks old version, I don't know why.

2022-12-21 15:18 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/ErrorModel.cs
> +        [JsonPropertyName("message")]
I still see the attributes when I pull your branch.

2022-12-21 15:28 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/BaseResponse.cs
> +    public class BaseResponse<TData>
I don't really understand your concern. 

> I have to use base response to return error or data.

You can use exceptions to return errors (including rich information about the error) and use normal models as return values from methods. In C# it's more common to use exceptions for error handling than to return error codes which have to be checked all the times. Hence code with exceptions is often cleaner to read. 

> writing same business code again and again

If you are talking about using a common `SendRequest` function that is used by all other functions like `BatchGetUsers` and `GetUser` then it can throw exceptions too. But that's part of the implementation too

```
// This can throw AuthServerErrorResponseException too, this doesn't have to return `BaseResponse<whatever>`.
private Task<TResponse> SendRequest<TResponse>(HttpMethod method, object body, ...);
```

2022-12-21 15:34 UTC, konstantin-smolyakov-idt commented on n2p-auth-service-client.sln
>  # Visual Studio Version 17
@irempehlivan You are posting part of implementation.  The disadvantage of what you are posting is that it's hardcoded which header is used and how. So in this way this library couldn't be used in a console or mobile application. Also, what if the service decides to pass the token as `X-Token` header instead of `Authorization`? Then this code becomes useless because it's not possible to customize it.

So we should introduce a public interface that client could provide to customize how token is extracted and from where. It could be from a file or from a http request or manually input from the user. Our library should not care about how that token is provided.

2022-12-21 15:39 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/AuthServerUnknownErrorResponseException.cs
> +    internal class AuthServerUnknownErrorResponseException : AuthServiceResponseException
@irempehlivan I still see no error details for this exception type. I expect information to be preserved, so that customers can log this information if they get an unknown response.

2022-12-21 15:42 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/AuthServerKnownErrorResponseException.cs
> +namespace N2P.Auth.Service.Client.ErrorHandling
@irempehlivan I see `// ReSharper disable once CheckNamespace` is used. We should use `Namespace Provider` toggle instead and commit Rider settings to source control instead (`.DotSettings` file). See here: https://www.jetbrains.com/help/rider/Refactorings__Adjust_Namespaces.html

2022-12-21 15:43 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/HttpClientTimeoutException.cs
> +public class HttpClientTimeoutException : Exception
@irempehlivan I still see an old name. Let's rename to `AuthServiceClientTimeoutException` to make sure it's distinguishable from other exception types.

2022-12-21 15:49 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/BatchGetUsers/AvatarImageModel.cs
> +    [JsonConverter(typeof(N2PJsonEnumStringConverter<AvatarImageKind>))]
@irempehlivan I still see JSON attributes that are relevant to implementation part. We can add them later if we decide to use attributes or we can use global JSON serialization settings per library. Let's keep clean data models in this PR without serialization specific details for now.

2022-12-21 15:51 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/Model/RawErrorResponse.cs
> +public class RawErrorResponse
@irempehlivan This is still unused. Let's either remove or use this model somewhere.

2022-12-21 16:15 UTC, konstantin-smolyakov-idt requested changes

2022-12-21 16:15 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/HttpClientTimeoutException.cs
> +    public static HttpClientTimeoutException Create<TService>(
**design (blocking)** Remove implementation bits for now. Also, the `TService` doesn't make any sense here as the library is only for the auth service know, so we can't share this type.

2022-12-21 16:15 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/InternalServerErrorModel.cs
> +        StatusCode = (int)HttpStatusCode.InternalServerError;
**design (blocking)** Status code will be read from JSON, we shouldn't set it manually.

2022-12-21 16:15 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/ValidationErrorModel.cs
> +    private ValidationErrorModel(string message,
**design (blocking)** Those constructors don't look necessary here anymore, because we'll deserialize errors from JSON mostly.

2022-12-21 16:15 UTC, konstantin-smolyakov-idt commented on src/n2p-auth-service-client/ErrorHandling/ValidationErrorModel.cs
> +    private static ValidationErrorCode? MapErrorCode(string fluentValidationErrorCode)
**design (blocking)** This is code specific to the server-side of the auth server. For the library, we would just parse `ValidationErrorCode` from JSON. So no need to keep reference to `FluentValidation` here.

2023-01-03 08:43 UTC, konstantin-smolyakov-idt approved these changes

2023-01-03 08:43 UTC, konstantin-smolyakov-idt commented on README.md
> +n2p-auth-service-client
**style (non blocking)** Use some proper markdown syntax to structure the readme file, e.g. headings

```suggestion
# net2phone Auth Service Client
```

2023-01-03 08:43 UTC, konstantin-smolyakov-idt commented on README.md
> +Initialize : Firstly,you should initialize the auth service client. So, to configure the client we can use the next code
**nit (non blocking)**
```suggestion
This project allows any project to quickly consume Auth Server V2 APIs in a .NET project. To do so:

1. Implement a `IAuthServiceClientTokenProvider` interface to provide access token being used.
2. Configure necessary options.

```

2023-01-03 08:43 UTC, konstantin-smolyakov-idt commented on README.md
> +Integrate the package to the service/application When package created an deployed to the NuGet feed we can install the package from IDE (Visual Studio, Rider) or even added as reference source in the
**suggestion (non blocking)** Let's add this when we have the CI and build pipeline. So for now I think we can remove this section.

2023-01-03 08:43 UTC, konstantin-smolyakov-idt commented on README.md
> +
**style (non blocking)**

Use code block styles to properly format code. Also, how the usage of options (and which options are available).

See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

```suggestion
```csharp
 using N2P.Auth.Service.Client;
 
 public void ConfigureServices(IServiceCollection services)
 {
    services.AddAuthServiceApiClient<CustomAuthServiceClientTokenProvider>(options => 
    {
      options.BaseUrl = "https://auth-qa.net2phone.com",
      options.Timeout = TimeSpan.FromSeconds(30)
    });
 }
```

```

2023-01-03 09:37 UTC, merged